server:
  servlet:
    context-path: /
    session:
      timeout: 30m
      tracking-modes: cookie
  encoding:
    charset: UTF-8
    enabled: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/adyb?serverTimezone=UTC&characterEncoding=UTF-8
    username: jkijki
    password: 1234
  messages:
    basename: errors

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false



